books = [
    {
        "id": 1,
        "title": "Think Python",
        "author": "Allen B. Downey",
        "publisher": "O'Reilly Media",
        "published_date": "2021-01-01",
        "page_count": 1234,
        "language": "English",
    },
    {
        "id": 2,
        "title": "Fluent Python",
        "author": "Luciano Ramalho",
        "publisher": "O'Reilly Media",
        "published_date": "2022-05-12",
        "page_count": 792,
        "language": "English",
    },
    {
        "id": 3,
        "title": "Python Crash Course",
        "author": "Eric Matthes",
        "publisher": "No Starch Press",
        "published_date": "2019-11-15",
        "page_count": 544,
        "language": "English",
    },
    {
        "id": 4,
        "title": "Effective Python",
        "author": "Brett Slatkin",
        "publisher": "Pearson",
        "published_date": "2020-08-30",
        "page_count": 256,
        "language": "English",
    },
    {
        "id": 5,
        "title": "Automate the Boring Stuff with Python",
        "author": "Al Sweigart",
        "publisher": "No Starch Press",
        "published_date": "2020-12-01",
        "page_count": 504,
        "language": "English",
    },
    {
        "id": 6,
        "title": "Python Tricks",
        "author": "Dan Bader",
        "publisher": "Dan Bader",
        "published_date": "2017-10-01",
        "page_count": 302,
        "language": "English",
    },
]